# Generated by Django 3.0.6 on 2020-11-14 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jexcel_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jexcel_crud.Book'),
            preserve_default=False,
        ),
    ]
